// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FilmResumed from "./islands/FilmResumed.tsx";
import * as $FilmsList from "./islands/FilmsList.tsx";
import * as $Searchbar from "./islands/Searchbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/FilmResumed.tsx": $FilmResumed,
    "./islands/FilmsList.tsx": $FilmsList,
    "./islands/Searchbar.tsx": $Searchbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
